---
version: '3.9'

services:
  jupyter:
    build: .
    image: jupyter:latest
    ports:
      - 8888:8888
    container_name: jupyter
    environment:
      - SHELL=/bin/bash
      - JUPYTER_TOKEN=0c73dfde57c3743e96e7c08683eacda192f4d5c6f8924e87
    command: [ "jupyter-lab","--ip=0.0.0.0","--no-browser" ]
    volumes:
      - ./local:/home/ansible/.ansible/local:rw